import type { Component } from 'vue'
import {
  GridOutline,
  SettingsOutline,
  PersonOutline,
  HomeOutline,
  ListOutline,
  InformationCircleOutline,
  MoonOutline,
  SunnyOutline,
  MenuOutline,
  CloseOutline,
  RefreshOutline,
  ExpandOutline,
  LogOutOutline,
  ColorPaletteOutline,
  DocumentTextOutline,
  SearchOutline,
  DownloadOutline,
  EyeOutline,
} from '@vicons/ionicons5'

export const iconMap: Record<string, Component> = {
  grid: GridOutline,
  settings: SettingsOutline,
  person: PersonOutline,
  home: HomeOutline,
  list: ListOutline,
  info: InformationCircleOutline,
  moon: MoonOutline,
  sunny: SunnyOutline,
  menu: MenuOutline,
  close: CloseOutline,
  refresh: RefreshOutline,
  expand: ExpandOutline,
  logout: LogOutOutline,
  palette: ColorPaletteOutline,
  log: DocumentTextOutline,
  search: SearchOutline,
  download: DownloadOutline,
  eye: EyeOutline,
}
