import type { Component } from 'vue'
import {
  GridOutline,
  SettingsOutline,
  PersonOutline,
  HomeOutline,
  ListOutline,
  InformationCircleOutline,
  MoonOutline,
  SunnyOutline,
  MenuOutline,
  CloseOutline,
  RefreshOutline,
  ExpandOutline,
  LogOutOutline,
  ColorPaletteOutline,
  DocumentTextOutline,
  SearchOutline,
  DownloadOutline,
  EyeOutline,
  VolumeHighOutline,
  MegaphoneOutline,
  SparklesOutline,
  PlayOutline,
  PauseOutline,
  StopOutline,
  TrashOutline,
  CopyOutline,
  FilmOutline,
  ImageOutline,
  PersonCircleOutline,
  GameControllerOutline,
  CalculatorOutline,
  TrophyOutline,
  TimerOutline,
  CheckmarkCircleOutline,
  CloseCircleOutline,
} from '@vicons/ionicons5'

export const iconMap: Record<string, Component> = {
  grid: GridOutline,
  settings: SettingsOutline,
  person: PersonOutline,
  home: HomeOutline,
  list: ListOutline,
  info: InformationCircleOutline,
  moon: MoonOutline,
  sunny: SunnyOutline,
  menu: MenuOutline,
  close: CloseOutline,
  refresh: RefreshOutline,
  expand: ExpandOutline,
  logout: LogOutOutline,
  palette: ColorPaletteOutline,
  log: DocumentTextOutline,
  search: SearchOutline,
  download: DownloadOutline,
  eye: EyeOutline,
  volume: VolumeHighOutline,
  megaphone: MegaphoneOutline,
  sparkles: SparklesOutline,
  play: PlayOutline,
  pause: PauseOutline,
  stop: StopOutline,
  trash: TrashOutline,
  copy: CopyOutline,
  film: FilmOutline,
  image: ImageOutline,
  about: PersonCircleOutline,
  game: GameControllerOutline,
  calculator: CalculatorOutline,
  trophy: TrophyOutline,
  timer: TimerOutline,
  checkmark: CheckmarkCircleOutline,
  closeCircle: CloseCircleOutline,
}
